config/routes.rb
Portal::Application.routes.draw do


  scope "(:locale)", :locale => /en|de/ do
  
    resources :announcements, :only => [ :index, :show] do
      get 'like', :on => :member
      get 'dislike', :on => :member
    end

    resources :home_page,     :only => [ :show ]

    match '/legal',                                    :to => 'static#legal'
    match '/annals',                                   :to => 'static#annals'
    match '/annals/results',                           :to => 'static#results', :as => 'annals_results'
    match '/special_offers',                           :to => 'static#special_offers'

    match :index,                                      :to => 'home_page#show'
    match '/invitations/:invitation',                  :to => 'home_page#show'
    match '/new_password/:id/:password_token',         :to => 'home_page#show'
    
    match '/return/:retention',                        :to => 'home_page#show'
    match '/invitations/:invitation',                  :to => 'home_page#show'
    match '/player_invitation/:player_invitation',     :to => 'home_page#show'
    match '/alliance_invitation/:alliance_invitation', :to => 'home_page#show'
    match '/new_password/:id/:password_token',         :to => 'home_page#show'

    # redirect for setting referer id directly in url http://wack-a-doo.de/r/1234
    match '/r/:r' => redirect { |p| "?r=#{p[:r]}" }
  end

  root :to => 'home_page#show'
  match :index, :to => 'home_page#show'
  match '/:locale' => 'home_page#show'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>" >
<head>
  <title>Wack-a-Doo<%= @title.blank? ? "" : " | #{@title}"  %></title>
  <%if @description%>
    <meta name="description" content="<%= @description %>" />
  <%end%>
  <link rel="shortcut icon" href="/assets/logo.ico" type="image/x-icon" />
  <meta name="google" content="notranslate">
  <%if @display_app_icon %>
    <meta name="apple-itunes-app" content="app-id=558781257">
  <%end%>

  <% I18n.available_locales.each do |locale| %>
    <link rel="alternate" hreflang="<%= locale.to_s %>" href="<%= (PORTAL_CONFIG['base_url'] || 'http://www.wack-a-doo.com') + '/' + locale.to_s %>" />
  <% end %>

  <script>
  
    var pathFragments = {
      'de_DE': '/de',
      'en_US': '/en',
    }
  
    window.currentLocale = "<%= I18n.t 'locale' %>";
    window.localePathFrag = pathFragments[window.currentLocale] || '/de'; // must change this to en as soon as internationalization is working
    window.startMsg = "<%= @message %>";
    
<% if @referer %>
    window.referer = "<%= @referer %>";
<% end %>

<% if !@invitation.nil? %>
    window.invitation = "<%= @invitation %>";
<% end %>

<% if !@player_invitation.nil? %>
    window.playerInvitation = "<%= @player_invitation %>";
<% end %>

<% if !@alliance_invitation.nil? %>
    window.allianceInvitation = "<%= @alliance_invitation %>";
<% end %>

<% if !@retention.nil? %>
    window.retention = "<%= @retention %>";
<% end %>

    // Google Analytics
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-33777536-1']);
    _gaq.push(['_trackPageview']);
  
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  <%= stylesheet_link_tag    "application" %>
  <%= yield(:javascript) %>
  <%= csrf_meta_tags %>
  
  <script>
    var getQueryVars = function(search)
    {
      var result = {};
    
      var parts = search.split('&');
      for (var i=0; i < parts.length; i++) {
        var item = parts[i].split("=");
        if (item.length === 2) {
          result[item[0].toLowerCase()] = decodeURIComponent(item[1]);
        }
      }
      return result;
    };
    
    var vars  = getQueryVars(window.location.search.substring(1));
    refid = vars['refid'] || vars['ref_id'];
    subid = vars['subid'] || vars['sub_id'];
    
    if (typeof window.Sample !== "undefined")
    {
      Sample.setEndpoint("/psiori/event")
      Sample.setAppToken("fsRrapvL");
      Sample.setModule("web-portal");
      Sample.setLocale(window.currentLocale || "unknown");
      Sample.setReferer(refid, subid);
      Sample.sessionStart();
      Sample.autoPing(30);
    }
  </script>
</head>
<body>

<%= content_for?(:content) ? yield(:content) : yield %>

</body>
</html>

app/views/layouts/landing_page.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag "application" %>
<% end %>

<% content_for :content do %>
  <%= content_for?(:fundamental_content) ? yield(:fundamental_content) : yield %>
<% end %>

<%= render :template => 'layouts/application' %>

app/views/layouts/standard.html.erb
<% content_for :javascript do %>
  <%= javascript_include_tag "application-libs" %>
<% end %>

<% content_for :content do %>
  <div id="top-controls" class="announcements">
    <%= link_to "en", params.merge(locale: :en) %> |
    <%= link_to "de", params.merge(locale: :de) %> &nbsp; &nbsp;
    <a href="http://www.facebook.com/pages/Wackadoo/239722582763809" target="_blank" id="facebook-link" >&nbsp;</a>
    <img class="img-preloader" src="<%= asset_path 'lp/fb-hover.png' %>">
  </div>

  <%= image_tag 'lp/logoswsmall.png', :id => 'wad-logo' %>


  <div id="menubar" class="menubarbackground">
    <ul>
      <li><%= link_to 'Home', root_url %></li>
      <li><%= link_to I18n.t('menue.news'), announcements_path %></li>
      <li><%= link_to I18n.t('menue.annals'), annals_path %></li>
      <!-- li><%= link_to I18n.t('menue.special_offers'), special_offers_path %></li -->
      <% if I18n.locale == :de %>

        <li><%= link_to I18n.t('menue.forum'), 'http://forum.wack-a-doo.com/', :target => '_blank' %></li>
        <li><%= link_to I18n.t('menue.blog'),  'http://blog.5dlab.com/',                    :target => '_blank' %></li>
        <li><%= link_to I18n.t('menue.wiki'),  'http://wiki.wack-a-doo.de/',                :target => '_blank' %></li>
      <% else %>  
        <li><%= link_to I18n.t('menue.wiki'),  'http://wiki.wack-a-doo.com/',               :target => "_blank" %></li>
      <% end %>
      
      <li><%= link_to 'Login', '.' %></li>
    </ul>
  </div>
  <div class="menubarbackground-bottom"></div>


  <%= content_for?(:fundamental_content) ? yield(:fundamental_content) : yield %>
  
  
  <br />

  <div id="sitemap">
    <ul>
      <li><%= link_to I18n.t('menue.agb'), :controller => :static, :action => :legal, :anchor => :terms %></li>
      <li><%= link_to I18n.t('menue.imprint'), :controller => :static, :action => :legal %></li>
    </ul>
  </div>  
<% end %>

<%= render :template => 'layouts/application' %>